### PR TITLE
Movielens fix #7

### LINKED ISSUE #7: key error when loading the validation dataset
I'm trying to compute movielens, after downloading movielens 20M, computing the data transformation, when I run the recommender:
`python run.py --gpu_ids 0 --path_to_train_data movielens/train --path_to_eval_data movielens/val --hidden_layers 512,512,1024 --non_linearity_type selu --batch_size 128 --logdir model_movielens --drop_prob 0.8 --optimizer momentum --lr 0.005 --weight_decay 0 --aug_step 1 --noise_prob 0 --num_epochs 1 --summary_frequency 1000`
I get an error:
```bash
Loading training data
Data loaded
Total items found: 138493
Vector dim: 20668
Loading eval data
Traceback (most recent call last):
  File "run.py", line 236, in <module>
    main()
  File "run.py", line 116, in main
    item_id_map=data_layer.itemIdMap)
  File "/home/hoaphumanoid/notebooks/repos/DeepRecommender/reco_encoder/data/input_layer.py", line 48, in __init__
    value = minor_map[int(parts[self._minor_ind])]
KeyError: 18223
```
  It looks that it is trying to find a key in the evaluation dataset that is not in the training dataset?

### PR DESCRIPTION
**Pull request by miguelgfierro**

### CODE REVIEW

**Comment by okuchaiev** [comment]
Looks good! Thanks you.
Have you tried running any experiments on Movielense?

**Comment by miguelgfierro** [comment]
I did, here the results so far using 1 NVIDIA P100:
```
*10 epochs,1gpu,bs=128,lr=0.005,hidden=512,512,1024,tr_time=1113s(18min),RMSE=0.8869814801625296
*50 epochs,1gpu,bs=256,lr=0.005,hidden=512,512,1024,tr_time=5026s(1.4h),RMSE=0.8500938244957209
*200 epochs,1gpu,bs=256,lr=0.005,hidden=512,512,1024,tr_time=19456s(5.4h),RMSE=0.8430963735001938

```
The rmse is lower than if you do ALS with a rank of 12, which I got 0.80. The next thing I will do is to try different layers. Have you done experiments with configurations in a diminishing order? like 512,512,256 or 512,256,128?

I noticed that when doing ALS if I use a rank of 200 I get RMSE of 0.97, but if I reduce the rank to 12 I get near 0.8. So maybe in this dataset we need a smaller latent space.

What is you experience on this?

**Comment by okuchaiev** [comment]
If ALS of rank 12 gets 0.80, I would try DeepRecommender with an architecture of 12,12.
Making first layer large (e.g. 512,....) is dangerous because it can trigger severe over-fitting, because then first fully connected layer will be of size num_movies_x_512. 
In fact, even with Netflix, the most time I spent fighting over-fitting.

**Comment by miguelgfierro** [comment]
ok, thank you for the guidance, I'll do experiments on my end and I will share them with you.

**Pull request merged**
